#!/bin/bash

RUNTYPE="$1"
if [ -z "$RUNTYPE" ]; then
    RUNTYPE="reportbrokenclient"
fi
MAC=`ifconfig en0 | awk '/ether/ {print $2}'`
SERIAL=`/usr/sbin/ioreg -l | grep IOPlatformSerialNumber | cut -f 4 -d \"`
NAME="$(echo `systemsetup -getcomputername | cut -d: -f2-`)"
SUBMITURL="http://kermit.cul.columbia.edu:8444/update"


curl --max-time 5 --silent \
    -d runtype="$RUNTYPE" \
    -d mac="$MAC" \
    -d serial="$SERIAL" \
    -d name="$NAME" \
    "$SUBMITURL/report_broken_client"

exit 0